# Configurações globais (fora de blocos)
ipc = true

# Novo formato de definição de papel de parede
wallpaper {
    monitor = 
    path = ~/.config/hypr/Wallpapers/wallpaper15.png
    # fit_mode = cover (opcional: contain, cover, tile ou fill)
}
